import { buildcoreAppDefinition } from '@/platform/appDefinitions/buildcore';

export const buildCoreDashboardContent = {
  loading: {
    page: 'Loading…',
  },
  licenseLockout: {
    title: 'You do not have a valid license',
    message:
      'Your license key is invalid or missing. Please contact your administrator to continue.',
  },
  branding: {
    defaultShopNameFallback: buildcoreAppDefinition.displayName,
    logoSaveFailedFallback: 'Failed to save logo',
  },
  dashboard: {
    title: 'Projects',
    overviewTitle: 'Overview',
    overviewBody: 'Pipeline metrics and reports will appear here in a later phase.',
    aboutSectionTitle: 'BuildCore',
    aboutSectionBody:
      'Construction/trades CRM shell: SaaS auth, ZenformedCore profile/entitlement relay, and shared dashboard chrome from @zenformed/core.',
  },
  crm: {
    resultCount: (filtered: number, total: number): string =>
      `Showing ${filtered} of ${total} projects`,
    filters: {
      toolbarAriaLabel: 'Project filters',
      stageLabel: 'Stage',
      stageAll: 'All stages',
      priorityLabel: 'Priority',
      priorityAll: 'All priorities',
    },
    create: {
      title: 'New project',
      closeAriaLabel: 'Close new project drawer',
      cancel: 'Cancel',
      submit: 'Create project',
      submitting: 'Creating…',
      submitFailed: 'Failed to create project. Please try again.',
      mockDisabledMessage:
        'Creating projects in the database requires NEXT_PUBLIC_CRM_DATA_SOURCE=api. Mock mode keeps existing demo data read-only.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to me',
      fields: {
        name: 'Project / customer name',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Current stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Deal value (USD)',
        balance: 'Balance remaining (USD)',
        assigned: 'Assigned to',
      },
    },
    table: {
      regionAriaLabel: 'All projects',
      empty: 'No projects match your search or filters.',
      unassigned: 'Unassigned',
      rowAriaLabel: (name: string): string => `Open project ${name}`,
      columns: {
        project: 'Project / customer',
        contact: 'Contact',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Deal value',
        balance: 'Balance',
        assigned: 'Assigned',
        updated: 'Updated',
      },
    },
  },
  projectDetail: {
    backToProjects: 'All projects',
    pageTitleFallback: 'Project',
    pipelineAriaLabel: 'Pipeline stage progress',
    currentStage: 'Current stage',
    unassigned: 'Unassigned',
    nextStepLabel: 'Next step',
    noNextStep: 'No blockers noted',
    notFound: {
      title: 'Project not found',
      message: 'This project does not exist or the link is invalid.',
      back: 'Back to projects',
    },
    sections: {
      contact: 'Contact & project',
      financials: 'Deal & payments',
      pipeline: 'Pipeline progress',
      workflow: 'Workflow tasks',
      documents: 'Documents',
      accountability: 'Accountability',
    },
    fields: {
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      customer: 'Customer',
      assigned: 'Assigned',
      updated: 'Last updated',
      dealValue: 'Deal value',
      balance: 'Balance remaining',
      invoiced: 'Invoiced',
      paid: 'Paid',
    },
    milestones: {
      empty: 'No milestones on file.',
    },
    edit: {
      title: 'Edit project',
      closeAriaLabel: 'Close edit project drawer',
      cancel: 'Cancel',
      submit: 'Save changes',
      submitting: 'Saving…',
      submitFailed: 'Failed to save project. Please try again.',
      notFound: 'Project not found.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to me',
      fields: {
        name: 'Project / customer name',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Current stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Deal value (USD)',
        balance: 'Balance remaining (USD)',
        assigned: 'Assigned to',
      },
    },
    editProjectButton: 'Edit project',
    saveSuccess: 'Changes saved.',
    saveError: 'Could not save changes.',
    workflow: {
      empty: 'No workflow tasks for this project.',
      addTask: 'Add task',
      editTask: 'Edit',
      archiveTask: 'Archive',
      documentsNone: '—',
      documentsCountSuffix: 'files',
      taskDrawerCreate: 'New workflow task',
      taskDrawerEdit: 'Edit workflow task',
      taskSubmit: 'Save task',
      taskSubmitting: 'Saving…',
      taskSubmitFailed: 'Failed to save task.',
      columns: {
        task: 'Task',
        stage: 'Stage',
        status: 'Status',
        documents: 'Documents',
        due: 'Due',
        actions: 'Actions',
      },
      fields: {
        title: 'Task title',
        stage: 'Stage',
        status: 'Status',
        due: 'Due date',
        notes: 'Notes',
        assigned: 'Assigned to',
      },
    },
    documents: {
      empty: 'No documents yet.',
      uploadHint: 'Uploads coming in a later phase.',
      columns: {
        name: 'Document',
        kind: 'Type',
        stage: 'Stage',
        uploaded: 'Uploaded',
        status: 'Status',
      },
      statusReviewed: 'Reviewed',
      statusPending: 'Pending review',
    },
    accountability: {
      empty: 'No activity logged yet.',
    },
  },
} as const;
