import { buildcoreAppDefinition } from '@/platform/appDefinitions/buildcore';

export const buildCoreDashboardContent = {
  loading: {
    page: 'Loading…',
  },
  licenseLockout: {
    title: 'You do not have a valid license',
    message:
      'Your license key is invalid or missing. Please contact your administrator to continue.',
  },
  corePlatform: {
    unavailableTitle: 'Core services temporarily unavailable',
    unavailableMessage:
      'Your session is valid, but Zenformed platform services could not be reached right now. Profile, licensing, and document storage should return when Core is back online.',
    retry: 'Try again',
    continueLimited: 'Continue with limited access',
    signOut: 'Sign out',
    degradedBannerTitle: 'Zenformed platform services are temporarily unavailable',
    degradedBannerLead:
      'You can keep working in BuildCore. Branding, profile photo, and document storage need Core and are temporarily paused until it is back\u00A0online.',
    degradedBannerAffected:
      'Temporarily unavailable: company logo & name · profile photo changes · document upload, download, and delete',
    degradedBannerDismissAriaLabel: 'Dismiss temporarily unavailable notice',
    retryCooldownHint: 'Please wait a moment before trying again.',
  },
  branding: {
    defaultShopNameFallback: buildcoreAppDefinition.displayName,
    logoSaveFailedFallback: 'Failed to save logo',
  },
  reports: {
    breadcrumb: 'CRM / Reports',
    title: 'Reports',
    loading: 'Loading reports…',
    loadError: 'Could not load reports data. Try again.',
    costsUndatedNote:
      'Some legacy costs used created date as Cost Date until backfilled.',
    periods: {
      mtd: 'Month To Date',
      qtd: 'Quarter To Date',
      ytd: 'Year To Date',
      all: 'All Time',
    },
    chartTabs: {
      revenue: 'Revenue',
      profit: 'Profit',
      costs: 'Costs',
      receivables: 'Receivables',
    },
    kpi: {
      collected: 'Collected Revenue',
      receivables: 'Receivables',
      netProfit: 'Net Profit',
    },
    sections: {
      projectPerformance: 'Project Performance',
      costBreakdown: 'Cost Breakdown',
    },
    table: {
      project: 'Project / Customer',
      collected: 'Collected',
      costs: 'Costs',
      profit: 'Profit',
      margin: 'Margin',
      status: 'Status',
      empty: 'No projects in this period.',
    },
    costEmpty: 'No costs in this period.',
  },
  dashboard: {
    title: 'Projects',
    overviewTitle: 'Overview',
    overviewBody: 'Pipeline metrics and reports will appear here in a later phase.',
    aboutSectionTitle: 'BuildCore',
    aboutSectionBody:
      'Construction/trades CRM shell: SaaS auth, ZenformedCore profile/entitlement relay, and shared dashboard chrome from @zenformed/core.',
  },
  crm: {
    resultCount: (filtered: number, total: number): string =>
      `Showing ${filtered} of ${total} projects`,
    filters: {
      toolbarAriaLabel: 'Project filters',
      stageLabel: 'Stage',
      stageAll: 'All stages',
      priorityLabel: 'Priority',
      priorityAll: 'All priorities',
    },
    create: {
      title: 'New project',
      closeAriaLabel: 'Close new project drawer',
      cancel: 'Cancel',
      submit: 'Create project',
      saveProject: 'Save project',
      cancelProject: 'Cancel',
      submitting: 'Creating…',
      submitFailed: 'Failed to create project. Please try again.',
      projectAddedSuccess: 'Project created.',
      mockDisabledMessage:
        'Creating projects in the database requires NEXT_PUBLIC_CRM_DATA_SOURCE=api. Mock mode keeps existing demo data read-only.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to me',
      fields: {
        name: 'Project / customer name',
        tradeType: 'Trade type',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Current stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Contract value (USD)',
        balance: 'Balance remaining (USD)',
        assigned: 'Assigned to',
      },
    },
    table: {
      regionAriaLabel: 'All projects',
      completionCheckAriaLabel: 'Project complete',
      empty: 'No projects match your search or filters.',
      unassigned: 'Unassigned',
      rowAriaLabel: (name: string): string => `Open project ${name}`,
      columns: {
        project: 'Project / customer',
        contact: 'Contact',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Contract value',
        assigned: 'Assigned',
        actions: 'Actions',
      },
    },
  },
  projectDetail: {
    backToProjects: 'All projects',
    pageTitleFallback: 'Project',
    pipelineAriaLabel: 'Pipeline stage progress',
    currentStage: 'Current stage',
    unassigned: 'Unassigned',
    projectNotesLabel: 'Notes',
    notFound: {
      title: 'Project not found',
      message: 'This project does not exist or the link is invalid.',
      back: 'Back to projects',
    },
    sections: {
      contact: 'Contact & project',
      financials: 'Contract & payments',
      pipeline: 'Pipeline progress',
      workflow: 'Workflow tasks',
      documents: 'Documents',
      accountability: 'Accountability',
    },
    fields: {
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      customer: 'Customer',
      assigned: 'Assigned',
      updated: 'Last updated',
      priority: 'Priority',
      dealValue: 'Contract value',
      balance: 'Balance due',
      invoiced: 'Invoiced',
      paid: 'Paid',
    },
    milestones: {
      empty: 'No milestones on file.',
    },
    edit: {
      title: 'Edit project',
      closeAriaLabel: 'Close edit project drawer',
      cancel: 'Cancel',
      submit: 'Save changes',
      submitting: 'Saving…',
      submitFailed: 'Failed to save project. Please try again.',
      notFound: 'Project not found.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to me',
      fields: {
        name: 'Project / customer name',
        tradeType: 'Trade type',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Current stage',
        waitingOn: 'Waiting on',
        notes: 'Notes',
        dealValue: 'Contract value (USD)',
        balance: 'Balance remaining (USD)',
        balanceDerivedHint: 'Balance is calculated from unpaid payment milestones.',
        assigned: 'Assigned to',
      },
    },
    actionsButton: 'Actions',
    markComplete: 'Mark as complete',
    markIncomplete: 'Mark incomplete',
    markCompleteConfirmTitle: 'Mark this project as complete?',
    markIncompleteConfirmTitle: 'Mark this project as incomplete?',
    markCompleteSuccess: 'Project marked as complete.',
    markIncompleteSuccess: 'Project marked as incomplete.',
    markCompleteFailed: 'Could not update project completion.',
    completionCheckAriaLabel: 'Project complete',
    actions: {
      workflowTasks: 'Workflow Tasks',
      accountability: 'Accountability',
      financials: 'Financials',
    },
    breadcrumbCrm: 'CRM',
    breadcrumbProjects: 'Projects',
    saveSuccess: 'Changes saved.',
    saveError: 'Could not save changes.',
    workflow: {
      empty: 'No workflow tasks for this project.',
      collapseStageTasks: 'Collapse stage tasks',
      expandStageTasks: 'Expand stage tasks',
      taskSingular: 'task',
      taskPlural: 'tasks',
      addTask: 'Add task',
      pickStage: 'Choose pipeline stage',
      taskAddedSuccess: 'Workflow task added.',
      saveTask: 'Save task',
      cancelTask: 'Cancel',
      editTask: 'Edit',
      archiveTask: 'Archive',
      deleteTask: 'Delete task',
      archiveTaskConfirmTitle: 'Delete task?',
      archiveTaskConfirmLabel: 'Delete',
      archiveTaskCancelLabel: 'Cancel',
      archiveTaskSuccess: 'Task deleted.',
      archiveTaskFailed: 'Could not delete task.',
      documentsNone: '—',
      documentsMarkRequired: 'Required',
      documentsNotRequired: 'N/A',
      documentsUpload: 'Upload',
      documentsUploadComingSoon: 'Uploads coming in a later phase.',
      documentUploadFailed: 'Could not upload document.',
      coreServicesUnavailable: 'Document storage is temporarily unavailable.',
      documentUploadSuccess: 'Document uploaded.',
      documentUploadConfirmTitle: 'Upload document?',
      documentUploadConfirmMessage: 'Upload “{fileName}” to “{taskTitle}”?',
      documentUploadConfirmLabel: 'Upload',
      documentDownload: 'Download',
      documentDelete: 'Delete',
      storageLimitExceeded: 'You have run out of document storage. Upgrade for more storage.',
      documentsCountSuffix: 'files',
      unassigned: 'Unassigned',
      taskDoneIndicator: 'Task complete',
      taskOpenIndicator: 'Task not complete',
      stageAllDone: 'All tasks in this stage are complete',
      taskDrawerCreate: 'New workflow task',
      taskDrawerEdit: 'Edit workflow task',
      taskSubmit: 'Save task',
      taskSubmitting: 'Saving…',
      taskSubmitFailed: 'Failed to save task.',
      paymentsGroupLabel: 'Payments',
      taskKindStandard: 'Standard task',
      taskKindPayment: 'Payment milestone',
      columns: {
        task: 'Task',
        stage: 'Stage',
        status: 'Status',
        documents: 'Documents',
        amount: 'Amount',
        assigned: 'Assigned',
        due: 'Due',
        actions: 'Actions',
      },
      viewAll: 'View all Workflow Tasks',
      openDocuments: 'Documents',
      fields: {
        title: 'Task title',
        stage: 'Stage',
        status: 'Status',
        documentsRequired: 'Documents required',
        documentsRequiredYes: 'Yes',
        documentsRequiredNo: 'No',
        due: 'Due date',
        notes: 'Notes',
        assigned: 'Assigned to',
        taskKind: 'Task type',
        amountUsd: 'Amount (USD)',
      },
    },
    payments: {
      title: 'Payments',
      addMilestone: 'Add payment milestone',
      empty: 'No payment milestones yet.',
      columns: {
        invoiced: 'Invoiced',
        paid: 'Paid',
      },
      milestoneDrawerCreate: 'New payment milestone',
      milestoneDrawerEdit: 'Edit payment milestone',
      saveMilestone: 'Save payment milestone',
      cancelMilestone: 'Cancel',
    },
    documents: {
      empty: 'No documents yet.',
      uploadHint: 'Uploads coming in a later phase.',
      filterAriaLabel: 'Filter documents',
      filters: {
        all: 'All',
        uploaded: 'Uploaded',
        missing: 'Missing',
      },
      noStage: 'No stage',
      missingForTask: 'Required for task',
      placeholderMeta: 'Required · not uploaded',
      placeholders: ['Signed estimate', 'Site photos', 'Permit packet'],
      viewAll: 'View all documents',
      columns: {
        name: 'Document',
        kind: 'Type',
        stage: 'Stage',
        uploaded: 'Uploaded',
        status: 'Status',
      },
      statusReviewed: 'Reviewed',
      statusPending: 'Pending review',
    },
    accountability: {
      empty: 'No activity logged yet.',
      viewAll: 'View all Accountability',
      columns: {
        dateTime: 'Date / Time',
        user: 'User',
        event: 'Event',
        entity: 'Entity',
        details: 'Details',
      },
    },
    budget: {
      tableTitle: 'Budget',
      addItem: 'Add budget item',
      empty: 'No budget items yet.',
      filterAriaLabel: 'Filter budget by category',
      itemNameRequired: 'Item name is required.',
      itemNamePlaceholder: 'Item name',
      saveItem: 'Save budget item',
      cancelItem: 'Cancel',
      deleteItem: 'Delete budget item',
      deleteItemConfirmTitle: 'Delete budget item?',
      deleteItemConfirmLabel: 'Delete',
      deleteItemCancelLabel: 'Cancel',
      deleteItemSuccess: 'Budget item deleted.',
      deleteItemFailed: 'Could not delete budget item.',
      totalsLabel: 'Totals',
      columns: {
        itemName: 'Item Name',
        category: 'Category',
        cost: 'Cost',
        budget: 'Budget',
        costDate: 'Cost Date',
        documents: 'Documents',
        remaining: 'Remaining',
      },
      costDateRequired: 'Cost Date is required.',
      categoryLabels: {
        labor: 'Labor',
        materials: 'Materials',
        equipment: 'Equipment',
        subcontractors: 'Subcontractors',
        permits: 'Permits',
        travel: 'Travel',
        lodging: 'Lodging',
        per_diem: 'Per Diem',
        fuel: 'Fuel',
        dump_disposal: 'Dump / Disposal Fees',
        rental_fees: 'Rental Fees',
        insurance: 'Insurance',
        office_admin: 'Office / Admin',
        other: 'Other',
      },
      pl: {
        title: 'Project Cost',
        generatePl: 'Generate P&L',
        exportError: 'Could not generate the P&L PDF. Please try again.',
        categoryName: 'Name',
        categoryCost: 'Cost',
        noCategories: 'No costs recorded yet.',
        totalBudget: 'Total Budget',
        totalCost: 'Total Cost',
        remaining: 'Remaining',
        overBudget: 'Over Budget',
        dealValue: 'Contract value (reference)',
      },
    },
  },
} as const;
