import { buildcoreAppDefinition } from '@/platform/appDefinitions/buildcore';
import type { ResolvedEntityTerminology } from '@/domain/buildcore/entityTerminology';
import { resolveEntityTerminology } from '@/domain/buildcore/entityTerminology';
import { deepResolveEntityTerminologyTokens } from '@/platform/content/resolveEntityTerminologyTokens';

const buildCoreDashboardContentSource = {
  loading: {
    page: 'Loading…',
  },
  licenseLockout: {
    title: 'You do not have a valid license',
    message:
      'Your license key is invalid or missing. Please contact your administrator to continue.',
  },
  corePlatform: {
    unavailableTitle: 'Core services temporarily unavailable',
    unavailableMessage:
      'Your session is valid, but Zenformed platform services could not be reached right now. Profile, licensing, and document storage should return when Core is back online.',
    retry: 'Try again',
    continueLimited: 'Continue with limited access',
    signOut: 'Sign out',
    degradedBannerTitle: 'Zenformed platform services are temporarily unavailable',
    degradedBannerLead:
      'You can keep working in BuildCore. Branding, profile photo, and document storage need Core and are temporarily paused until it is back\u00A0online.',
    degradedBannerAffected:
      'Temporarily unavailable: company logo & name · profile photo changes · document upload, download, and delete',
    degradedBannerDismissAriaLabel: 'Dismiss temporarily unavailable notice',
    retryCooldownHint: 'Please wait a moment before trying again.',
  },
  branding: {
    defaultShopNameFallback: buildcoreAppDefinition.displayName,
    logoSaveFailedFallback: 'Failed to save logo',
  },
  reports: {
    breadcrumb: 'CRM / Reports',
    title: 'Reports',
    loading: 'Loading reports…',
    loadError: 'Could not load reports data. Try again.',
    costsUndatedNote:
      'Some legacy costs used created date as Cost Date until backfilled.',
    periods: {
      mtd: 'Month To Date',
      qtd: 'Quarter To Date',
      ytd: 'Year To Date',
      all: 'All Time',
    },
    chartTabs: {
      revenue: 'Revenue',
      profit: 'Profit',
      costs: 'Costs',
      receivables: 'Receivables',
    },
    kpi: {
      collected: 'Collected Revenue',
      receivables: 'Outstanding Receivables',
      netProfit: 'Net Profit',
      activeProjects: 'Active §E2§',
      pipelineValue: 'Pipeline Value',
      foot: {
        payments: 'Payments',
        avgPayment: 'Avg Payment',
        unpaid: 'Unpaid',
        overdue: 'Overdue',
        margin: 'Margin',
        avgDaysToPay: 'Avg Days To Pay',
        waitingApproval: 'Waiting Approval',
        overduePayments: 'Overdue Payments',
        unpaidBalance: 'Unpaid',
        activeProjects: 'Active §E2§',
      },
    },
    sections: {
      dailyRevenueCosts: 'Revenue & Costs',
      projectPerformance: '§E1§ Performance',
      costBreakdown: 'Budget Cost Breakdown',
      recentActivity: 'Recent Activity',
    },
    charts: {
      revenueCollected: 'Revenue Collected',
      costs: 'Costs',
      profit: 'Profit',
      totalCosts: 'Total Costs',
    },
    projectFilters: {
      all: 'All',
      active: 'Active',
      completed: 'Completed',
      waiting_approval: 'Waiting Approval',
      overdue_payments: 'Overdue Payments',
    },
    projectPerformanceMobile: {
      filterAriaLabel: 'Filter §E5§ performance',
    },
    table: {
      project: '§E1§',
      collected: 'Revenue',
      costs: 'Cost',
      profit: 'Profit',
      margin: 'Margin',
      status: 'Status',
      empty: 'No §E6§ in this period.',
      emptyFiltered: 'No §E6§ match this filter.',
    },
    activity: {
      empty: 'No financial activity in this period.',
    },
    costEmpty: 'No costs in this period.',
    costBreakdownTable: {
      category: 'Category',
      cost: 'Cost',
      costPercent: 'Cost %',
    },
    downloadPdf: 'Download PDF',
    downloadPdfGenerating: 'Generating…',
    downloadPdfError: 'Could not generate the report PDF. Please try again.',
    pdfExport: {
      menuLabel: 'Reports',
      currentReport: 'Current Report',
      downloadCurrent: 'Download Current',
      reportPeriod: 'Report Period',
    },
    organizationExport: {
      buttonLabel: 'Export Data',
      exporting: 'Exporting…',
      error: 'Could not export organization data. Please try again.',
    },
    mobileControls: {
      reportRangeLabel: 'Report Range',
      reportRangeAriaLabel: 'Report range',
      sectionLabel: 'Report Section',
      sectionAriaLabel: 'Report section',
    },
    yearlyPdf: {
      reportTitle: 'BuildCore Financial Report',
    },
    summaryPdf: {
      revenue: 'Revenue',
      collectedRevenue: 'Collected Revenue',
      totalRevenue: 'Total Revenue',
      costOfGoodsSold: 'Cost of Goods Sold',
      totalCostOfGoodsSold: 'Total Cost of Goods Sold',
      grossMargin: 'Gross Margin',
      operatingExpenses: 'Operating Expenses',
      totalOperatingExpenses: 'Total Operating Expenses',
      netProfit: 'Net Profit (Loss)',
      footerNote:
        'Revenue, gross margin, operating expenses, and net profit percentages are based on total revenue. Cost detail percentages are based on total cost of goods sold.',
    },
  },
  dashboard: {
    title: '§E2§',
    overviewTitle: 'Overview',
    overviewBody: 'Pipeline metrics and reports will appear here in a later phase.',
    aboutSectionTitle: 'BuildCore',
    aboutSectionBody:
      'Construction/trades CRM shell: SaaS auth, ZenformedCore profile/entitlement relay, and shared dashboard chrome from @zenformed/core.',
  },
  demo: {
    banner: {
      title: 'Interactive Demo',
      message: 'Changes stay inside this demo and never affect real data.',
      closeDemo: 'Close Demo',
      resetDemo: 'Reset Demo',
      startFreeTrial: 'Start Free Trial',
      pricingSectionId: 'buildcore-pricing',
      collapseBanner: 'Collapse demo banner',
      expandBanner: 'Expand demo banner',
    },
    shell: {
      appLauncherDisabledTitle: 'App switching is disabled in the interactive demo.',
      accountMenuDisabledTitle: 'Account settings are disabled in the interactive demo.',
    },
    exportDisabledMessage: 'Export is disabled in the interactive demo.',
  },
  workflowStages: {
    breadcrumb: 'Organization / Workflow Stages',
    title: 'Workflow Stages',
    listTitle: 'Stages',
    loading: 'Loading workflow stages…',
    loadError: 'Could not load workflow stages. Try again.',
    noAccess: 'You do not have permission to manage workflow stages for this organization.',
    readOnlyNote: 'Workflow stages are managed by organization owners and admins.',
    addStage: 'Add Stage',
    addStageTitle: 'Add workflow stage',
    editStageTitle: 'Rename workflow stage',
    deleteStageTitle: 'Delete workflow stage?',
    deleteStageMessage: (name: string) =>
      `Delete "${name}"? This cannot be undone if the stage is not used by any §E6§ or tasks.`,
    stageNameLabel: 'Stage name',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    empty: 'No workflow stages yet.',
    editStageAriaLabel: (name: string) => `Edit ${name}`,
    deleteStageAriaLabel: (name: string) => `Delete ${name}`,
    reservedStageDeleteHint: 'Complete is the terminal stage and cannot be deleted.',
    reorderFailed: 'Could not reorder workflow stages. Please try again.',
  },
  workflowSettings: {
    breadcrumb: 'Organization / Workflow Settings',
    title: 'Workflow Settings',
    loading: 'Loading workflow settings…',
    loadError: 'Could not load workflow settings. Try again.',
    noAccess: 'You do not have permission to manage workflow settings for this organization.',
    readOnlyNote: 'Workflow settings are managed by organization owners and admins.',
    introNote: 'Manage workflow stages for §E5§ and §E7§ stages.',
    folderTabs: {
      workflowStages: 'Workflow Stages',
      alerts: 'Customer Task Alerts',
    },
    desktopNav: {
      workflowStages: 'Workflow Stages',
      alerts: 'Alerts',
      ariaLabel: 'Workflow settings',
    },
    stageColumns: {
      projectStages: '§E1§ Stages',
      subprojectStages: '§E3§ Stages',
    },
    alerts: {
      customerTaskReminders: {
        enableLabel: 'Enable automatic customer reminders',
        enableHint:
          'Send follow-up emails to customers with open assigned tasks after the selected interval. Initial assignment emails are unchanged.',
        frequencyLabel: 'Frequency',
        frequencyHint:
          'Reminders begin after the selected interval from the last assignment or reminder email. Rejected tasks continue receiving reminders until the task is submitted for approval or marked done.',
        loading: 'Loading reminder settings…',
        loadError: 'Could not load reminder settings. Try again.',
        readOnlyNote: 'Only organization owners and admins can change alert settings.',
        saved: 'Reminder settings saved.',
      },
    },
  },
  teams: {
    breadcrumb: 'Organization / Teams',
    title: 'Teams',
    loading: 'Loading team members…',
    loadError: 'Could not load team data. Try again.',
    noAccess: 'You do not have permission to view team members for this organization.',
    architectureNote:
      'Organization membership controls organization-level access. BuildCore permissions are for app-specific operational access.',
    sections: {
      organizationMembership: 'Organization Membership',
      organizationMembershipHint:
        'Who belongs to your organization and their organization-level role.',
      buildCoreAccess: 'BuildCore Access',
      buildCoreAccessHint:
        'Whether each member can use BuildCore. This is separate from organization membership.',
      buildCorePermissions: 'BuildCore Permissions',
      buildCorePermissionsHint: 'App-specific roles and capabilities.',
      assignmentPermissions: 'Assignment / Approval Permissions',
      assignmentPermissionsHint: 'Workflow assignment and approval rules (coming soon).',
    },
    placeholders: {
      permissionsComingSoon: 'Permission editing will be available in a future release.',
      assignmentComingSoon: 'Assignment and approval rules will be configured here later.',
      actionsComingSoon: 'Coming soon',
      buildCoreRoleUnset: 'Not assigned',
    },
    table: {
      title: 'Members',
      regionAriaLabel: 'Organization members and BuildCore access',
      name: 'Name',
      email: 'Email',
      role: 'Role',
      organizationRole: 'Organization role',
      buildCoreAccess: 'BuildCore access',
      buildCoreAccessToggleAriaLabel: 'BuildCore access',
      access: 'Access',
      buildCoreRole: 'BuildCore role',
      actions: 'Actions',
      empty: 'No team members found.',
    },
    accessStatus: {
      enabled: 'Enabled',
      notConfigured: 'Not configured',
    },
    permissionsExpand: 'Expand section',
    permissionsCollapse: 'Collapse section',
    folderTabs: {
      members: 'Members',
      taskPermissions: 'Task Permissions',
      paymentPermissions: 'Payment Permissions',
      budgetPermissions: 'Budget Permissions',
    },
    desktopNav: {
      members: 'Members',
      permissions: 'Permissions',
      ariaLabel: 'Team settings',
    },
    mobileControls: {
      sectionLabel: 'Section',
      sectionAriaLabel: 'Team section',
    },
    demo: {
      viewOnlyBannerTitle: 'Team management is view-only in the interactive demo.',
      viewOnlyBannerMessage:
        'Start your own workspace to invite team members, assign roles, and collaborate with your team.',
      startFreeTrial: 'Start Free Trial',
      permissionsReadOnlyNote:
        'Permission changes are view-only in the interactive demo.',
      accessToggleDisabledTitle: 'BuildCore access cannot be changed in the interactive demo.',
    },
    workflowTaskPermissions: {
      title: 'Workflow Task Permissions',
      hint: 'Control what each BuildCore role can do with workflow tasks.',
      roleColumn: 'Role',
      loading: 'Loading workflow task permissions…',
      empty: 'No permission settings available.',
      memberVisibility: {
        toggleLabel: 'Only assigned user can view',
        defaultNote: 'Default: Enabled',
        hint: 'When enabled, members only see workflow tasks assigned to themselves. When disabled, members see tasks assigned to any member-role user.',
        loading: 'Loading member visibility setting…',
      },
    },
    paymentPermissions: {
      title: 'Payment Permissions',
      hint: 'Control what each BuildCore role can do with payment milestones.',
      roleColumn: 'Role',
      loading: 'Loading payment permissions…',
      empty: 'No permission settings available.',
      memberVisibility: {
        toggleLabel: 'Only assigned user can view',
        defaultNote: 'Default: Enabled',
        hint: 'When enabled, members only see payment milestones assigned to themselves. When disabled, members see payment milestones assigned to any member-role user.',
        loading: 'Loading member visibility setting…',
      },
    },
    budgetPermissions: {
      title: 'Budget Permissions',
      hint: 'Control what each BuildCore role can do with §E5§ budget items.',
      roleColumn: 'Role',
      loading: 'Loading budget permissions…',
      empty: 'No permission settings available.',
    },
  },
  crm: {
    panel: {
      title: '§E2§',
      searchPlaceholder: 'Search §E6§…',
      searchAriaLabel: 'Search §E6§',
      expandAllSubprojects: 'Expand all §E8§',
      collapseAllSubprojects: 'Collapse all §E8§',
      listView: {
        toggleAriaLabel: 'Switch list view',
        menuAriaLabel: 'Dashboard list view',
        projects: '§E2§',
        subprojects: '§E4§',
        showProjects: 'Show §E6§',
        showSubprojects: 'Show §E8§',
        parentProjectColumn: '§E1§',
        parentProjectLabel: (name: string): string => `§E1§: ${name}`,
      },
    },
    myTasks: {
      title: 'My Tasks',
      sidebarLabel: 'My Tasks',
      sidebarTitle: 'My Tasks',
      loading: 'Loading your tasks…',
      loadFailed: 'Could not load your tasks. Try again.',
      empty: "You don't have any tasks assigned to you yet.",
      emptyFiltered: 'No tasks match this assignee filter.',
      projectContextLabel: '§E1§',
      subprojectContextLabel: '§E3§',
      paymentContextLabel: 'Payment',
      assigneeFilterAriaLabel: 'Filter tasks by assignee',
      assigneeScopeMine: 'Mine',
      assigneeScopeOthers: 'Other members',
      assigneeScopeEveryone: 'Everyone',
      openTaskAriaLabel: (title: string): string => `Open task ${title}`,
      expandProjectTasks: (projectName: string): string => `Show tasks for ${projectName}`,
      collapseProjectTasks: (projectName: string): string => `Hide tasks for ${projectName}`,
      taskCountLabel: (count: number): string => (count === 1 ? '1 task' : `${count} tasks`),
      searchPlaceholder: 'Search tasks…',
      searchAriaLabel: 'Search tasks',
      emptySearch: 'No tasks match your search.',
      projectNameLabel: 'Project',
      contactLabel: 'Customer',
      emailLabel: 'Email',
      phoneLabel: 'Phone Number',
      addressLabel: 'Address',
      projectPreviewAriaLabel: (projectName: string): string =>
        `Project details for ${projectName}`,
      detail: {
        backToMyTasks: 'Back to My Tasks',
        breadcrumbAriaLabel: 'Task location',
        customerHeading: 'Customer',
        assignmentHeading: 'Assignment',
        titleLabel: 'Title',
        notesLabel: 'Notes',
        dueLabel: 'Due',
        statusLabel: 'Status',
        stageLabel: 'Stage',
        paymentLabel: 'Payment',
        amountLabel: 'Amount',
        documentsLabel: 'Attachments',
        noDocuments: 'No attachments',
        noNotes: 'No notes',
        completeAction: 'Complete',
        completeNeedsReview: 'Submit for approval',
        inReviewBanner: 'IN REVIEW',
        inReviewInline: 'In Review',
        taskCompleteBanner: 'Task Complete',
        completedTaskLocked: 'Completed',
        completedTasks: 'Completed Tasks',
        expandCompletedTasks: 'Show completed tasks',
        collapseCompletedTasks: 'Hide completed tasks',
        noActiveTasks: 'No active tasks.',
        completeSuccess: 'Task updated.',
        completeFailed: 'Could not update task status.',
        inactiveBlocked:
          'This §E5§ is inactive. Mark it active before updating this task.',
        notFound: 'Task not found.',
        phonesLabel: 'Phone',
        emailsLabel: 'Email',
        addressLabel: 'Address',
      },
    },
    filters: {
      openMenu: 'Filter §E6§',
      menuAriaLabel: '§E1§ filters',
      clear: 'Clear filters',
      stageLabel: 'Stage',
      priorityLabel: 'Priority',
      statusLabel: 'Status',
      assignedLabel: 'Assigned',
      documentsRequiredLabel: 'Documents required',
      documentsRequiredYes: 'Yes',
      documentsRequiredNo: 'No',
      radius: {
        sectionLabel: 'Radius',
        zipCodeLabel: 'ZIP Code',
        radiusLabel: 'Radius',
        milesUnit: 'miles',
        clearZipCodeAriaLabel: 'Clear ZIP code',
        sliderAriaLabel: 'Radius in miles',
        zipCodeAriaLabel: 'ZIP code for radius filter',
        radiusInputAriaLabel: 'Radius distance in miles',
      },
    },
    assignee: {
      customer: 'Assign to Customer',
      self: 'Assign to myself',
    },
    create: {
      title: 'New §E5§',
      closeAriaLabel: 'Close new §E5§ modal',
      cancel: 'Cancel',
      submit: 'Create §E5§',
      saveProject: 'Save §E5§',
      cancelProject: 'Cancel',
      submitting: 'Creating…',
      submitFailed: 'Failed to create §E5§. Please try again.',
      projectAddedSuccess: '§E1§ created.',
      mockDisabledMessage:
        '§E1§ creation is not available in this environment.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to myself',
      fields: {
        name: '§E1§ / customer name',
        industry: 'Industry',
        customIndustry: 'Custom industry',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        emailAddresses: 'Email addresses (up to 4)',
        phoneNumbers: 'Phone numbers (up to 4)',
        addEmail: '+ Add email',
        removeEmail: 'Remove email address',
        removeEmailConfirm: {
          title: 'Remove email address?',
          body: 'This email address will be removed when you save the §E5§.',
          confirm: 'Remove',
          cancel: 'Cancel',
          closeAriaLabel: 'Close remove email dialog',
        },
        addPhone: '+ Add phone',
        removePhone: 'Remove phone number',
        removePhoneConfirm: {
          title: 'Remove phone number?',
          body: 'This phone number will be removed when you save the §E5§.',
          confirm: 'Remove',
          cancel: 'Cancel',
          closeAriaLabel: 'Close remove phone dialog',
        },
        priority: 'Priority',
        stage: 'Current stage',
        notes: 'Notes (Max 200)',
        assigned: 'Assigned to',
        assignedShort: 'Assigned',
        addressLine1: 'Address line 1',
        addressLine2: 'Address line 2 (optional)',
        city: 'City',
        state: 'State',
        postalCode: 'Zip code',
      },
    },
    projectCustomFields: {
      project: {
        sectionTitle: '§E1§ custom fields',
        empty: 'No §E5§ custom fields yet.',
        addButton: '+ Add custom field',
        unsupportedType: 'This field type is not supported yet.',
        removeAriaLabel: (label: string): string => `Delete custom field ${label}`,
      },
      subproject: {
        sectionTitle: '§E3§ custom fields',
        empty: 'No §E7§ custom fields yet.',
        addButton: '+ Add custom field',
        unsupportedType: 'This field type is not supported yet.',
        removeAriaLabel: (label: string): string => `Delete custom field ${label}`,
      },
    deleteField: {
      title: (label: string): string => `Delete "${label}"?`,
      bodyProject:
        'This action is irreversible. The field will be removed from all §E6§ in your organization, and any values stored in this field will be erased.',
      bodySubproject:
        'This action is irreversible. The field will be removed from all §E8§ in your organization, and any values stored in this field will be erased.',
      confirm: 'Delete field',
      cancel: 'Cancel',
      deleting: 'Deleting…',
      failed: 'Could not delete custom field.',
      closeAriaLabel: 'Close delete custom field dialog',
    },
      addDialogTitle: 'Add custom field',
      labelField: 'Label',
      typeField: 'Type',
      typeText: 'Text',
      addConfirm: 'Add field',
      creating: 'Adding…',
      createFailed: 'Could not create custom field.',
      closeAriaLabel: 'Close add custom field dialog',
      unsupportedType: 'This field type is not supported yet.',
      emptyValue: '—',
    },
    projectPreview: {
      ariaLabel: (name: string): string => `§E1§ preview for ${name}`,
      showPreviewAriaLabel: (name: string): string => `Show preview for ${name}`,
      hidePreviewAriaLabel: 'Hide §E5§ preview',
      kindProject: '§E1§',
      kindSubproject: '§E3§',
      viewDetails: 'View details',
      loading: 'Loading…',
      loadFailed: 'Could not load preview.',
      labels: {
        contact: 'Contact',
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
        assigned: 'Assigned',
        industry: 'Industry',
        stage: 'Stage',
        progress: 'Progress',
        notes: 'Notes',
      },
      sections: {
        overview: 'Overview',
        notes: 'Notes',
        customFields: 'Custom fields',
      },
    },
    table: {
      regionAriaLabel: 'All §E6§',
      completionCheckAriaLabel: '§E1§ complete',
      priorityMarkAriaLabel: 'Priority §E5§',
      empty: 'No §E6§ match your search or filters.',
      emptyMemberNoAssignments: "You don't have any tasks assigned to you yet.",
      unassigned: 'Unassigned',
      expandSubprojects: 'Show §E8§',
      collapseSubprojects: 'Hide §E8§',
      rowAriaLabel: (name: string): string => `Open §E5§ ${name}`,
      subprojectRowAriaLabel: (name: string): string => `Open §E7§ ${name}`,
      columns: {
        project: '§E1§ / customer',
        contact: 'Contact',
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
        priority: 'Priority',
        stage: 'Stage',
        notes: 'Notes',
        value: 'Value',
        collected: 'Collected',
        balance: 'Balance',
        projectValueLabel: '§E1§ Value',
        subValueLabel: 'Sub Value',
        assigned: 'Assigned',
        actions: 'Actions',
      },
      actionsMenuAriaLabel: (name: string): string => `Actions for ${name}`,
      deleteAction: 'Delete',
      makePriority: 'Make Priority',
      removePriority: 'Remove Priority',
      markComplete: 'Mark Complete',
      markIncomplete: 'Mark Incomplete',
      multiAssign: 'Multi assign',
      inactiveBadge: 'Inactive',
      makePrioritySuccess: '§E1§ marked as priority.',
      removePrioritySuccess: '§E1§ priority removed.',
      makePriorityFailed: 'Could not update §E5§ priority.',
      multiAssignSuccess: (count: number): string =>
        count === 1 ? 'Assigned 1 selected item.' : `Assigned ${count} selected items.`,
      multiAssignFailed: 'Could not update assignee.',
    },
    delete: {
      action: 'Delete §E1§',
      actionAriaLabel: (name: string): string => `Delete §E1§ ${name}`,
      confirmTitle: 'Delete this §E5§?',
      confirmMessage: (name: string): string =>
        `"${name}" will be removed from your §E5§ list.`,
      confirmLabel: 'Delete',
      cancelLabel: 'Cancel',
      success: '§E1§ deleted.',
      failed: 'Failed to delete §E5§. Try again.',
      notFound: '§E1§ not found.',
      mockDisabledMessage:
        '§E1§ deletion is not available in this environment.',
      workflow: {
        title: 'Delete §E1§',
        itemLabel: '§E5§',
        intentActionLabel: 'I want to delete this §E5§',
        finalActionLabel: 'Delete §E1§',
        consequenceDescription:
          'This action permanently deletes this §E5§ and all associated data.',
        affectedDataSummary:
          'Affected data includes §E4§, Workflow Tasks, Payments, Budget Entries, Documents, Reporting Data, and Accountability Records.',
      },
    },
  },
  bulkSelection: {
    select: 'Select',
    cancel: 'Cancel',
    selectAll: 'Select all visible',
    selectAllAriaLabel: 'Select all visible items',
    selectItemAriaLabel: (label: string): string => `Select ${label}`,
    selectedCount: (count: number): string => `${count} selected`,
    send: 'Send',
    sendAttachment: 'Send Attachment',
    deleteSelected: 'Delete selected',
    delete: 'Delete',
    actionsMenuAriaLabel: 'Bulk actions menu',
    toolbarAriaLabel: 'Bulk actions',
  },
  bulkDelete: {
    confirmPhrase: 'confirm delete',
    cancelLabel: 'Cancel',
    closeAriaLabel: 'Close bulk delete confirmation',
    failed: 'Failed to delete selected items. Try again.',
    partialFailure: (deletedCount: number, failedCount: number): string =>
      `Deleted ${deletedCount} item${deletedCount === 1 ? '' : 's'}, but ${failedCount} could not be deleted.`,
    success: (count: number, itemLabel: string): string =>
      `Deleted ${count} ${count === 1 ? itemLabel : `${itemLabel}s`}.`,
  },
  destructiveConfirmationWorkflow: {
    title: 'Delete Selected Items',
    intentActionLabel: 'I want to delete the selected items',
    consequencesAcknowledgeLabel: 'I have read and understand these effects',
    confirmationInstructions: (phrase: string): string =>
      `To confirm deletion type "${phrase}" in the box below`,
    irrevocableWarning: 'This action cannot be undone.',
    closeAriaLabel: 'Close destructive confirmation',
    finalActionLabel: 'Delete Selected Items',
    selectedCountMessage: (count: number, itemLabel: string): string =>
      `${count} ${count === 1 ? itemLabel : `${itemLabel}s`} selected`,
    moreItems: (count: number): string => `+ ${count} more`,
  },
  projectDetail: {
    backToProjects: 'All §E6§',
    pageTitleFallback: '§E1§',
    pipelineAriaLabel: 'Pipeline stage progress',
    currentStage: 'Current stage',
    unassigned: 'Unassigned',
    projectNotesLabel: 'Notes',
    primaryPhoto: {
      placeholderAriaLabel: '§E1§ photo',
      changeTitle: 'Change §E5§ photo',
      changeAriaLabel: 'Change §E5§ photo',
      modalTitle: '§E1§ photo',
      uploadLabel: 'Upload photo',
      removeLabel: 'Remove photo',
      cancelLabel: 'Cancel',
      uploadHint: 'JPEG, PNG, or WebP up to 2 MB.',
      uploadError: 'Could not update §E5§ photo.',
      removeError: 'Could not remove §E5§ photo.',
    },
    notFound: {
      title: '§E1§ not found',
      message: 'This §E5§ does not exist or the link is invalid.',
      back: 'Back to §E6§',
    },
    sections: {
      contact: 'Contact & §E5§',
      projectInformation: '§E1§ information',
      financials: 'Payments',
      pipeline: 'Pipeline progress',
      workflow: 'Workflow tasks',
      documents: 'Documents',
      accountability: 'Accountability',
    },
    folderTabs: {
      sectionsLabel: '§E1§ Sections',
      selectAriaLabel: '§E1§ section',
    },
    contactValues: {
      emailCopied: 'Email copied',
      phoneCopied: 'Phone copied',
      allEmailsAriaLabel: 'All email addresses',
      allPhonesAriaLabel: 'All phone numbers',
      copyEmailAriaLabel: (value: string): string => `Copy email ${value}`,
      copyPhoneAriaLabel: (value: string): string => `Copy phone ${value}`,
      showEmailsToggleAriaLabel: 'Show all email addresses',
      hideEmailsToggleAriaLabel: 'Hide email addresses',
      showPhonesToggleAriaLabel: 'Show all phone numbers',
      hidePhonesToggleAriaLabel: 'Hide phone numbers',
    },
    fullDetails: {
      title: '§E1§ details',
      viewDetails: 'View details',
      viewEdit: 'View/Edit',
      closeAriaLabel: 'Close §E5§ details',
      labels: {
        project: '§E1§',
        emails: 'Email list',
        phones: 'Phone list',
      },
      emptyValue: '—',
    },
    fields: {
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      customer: 'Customer',
      assigned: 'Assigned',
      updated: 'Last updated',
      priority: 'Priority',
      value: 'Value',
      projectValue: '§E1§ Value',
      subValue: 'Sub Value',
      collected: 'Collected',
      balance: 'Balance',
      invoiced: 'Invoiced',
      paid: 'Paid',
    },
    milestones: {
      empty: 'No milestones on file.',
    },
    edit: {
      title: 'Edit §E5§',
      closeAriaLabel: 'Close edit §E5§ drawer',
      cancel: 'Cancel',
      submit: 'Save changes',
      submitting: 'Saving…',
      submitFailed: 'Failed to save §E5§. Please try again.',
      notFound: '§E1§ not found.',
      assigneeUnassigned: 'Unassigned',
      assigneeSelf: 'Assign to myself',
      fields: {
        name: '§E1§ / customer name',
        industry: 'Industry',
        customIndustry: 'Custom industry',
        contactName: 'Contact name',
        email: 'Email',
        phone: 'Phone',
        priority: 'Priority',
        stage: 'Current stage',
        notes: 'Notes',
        balanceDerivedHint: 'Balance is calculated from unpaid payment milestones.',
        assigned: 'Assigned to',
      },
    },
    actionsButton: 'Actions',
    markComplete: 'Mark as complete',
    markIncomplete: 'Mark incomplete',
    markCompleteConfirmTitle: 'Mark this §E5§ as complete?',
    markCompleteConfirmMessage: 'This will set the §E5§ at 100%.',
    markCompleteBlockedTitle:
      'All Workflow Tasks Must be done before marking this §E5§ Complete',
    markCompleteBlockedStagesHeading: 'Workflow stages:',
    markCompleteBlockedDismiss: 'OK',
    markIncompleteConfirmTitle: 'Mark this §E5§ as incomplete?',
    markIncompleteConfirmMessage: 'Progress will reflect the current pipeline stage again.',
    markCompleteSuccess: '§E1§ marked as complete.',
    markIncompleteSuccess: '§E1§ marked as incomplete.',
    markCompleteFailed: 'Could not update §E5§ completion.',
    markPriority: 'Mark as priority',
    removePriority: 'Remove priority',
    completionCheckAriaLabel: '§E1§ complete',
    actions: {
      workflowTasks: 'Workflow Tasks',
      accountability: 'Accountability',
      financials: 'Financials',
      showQrCode: 'Show QR Code',
      refreshSection: 'Refresh',
      refreshSectionAria: (section: string): string => `Refresh ${section}`,
      refreshingSection: 'Refreshing…',
      refreshingSectionAria: (section: string): string => `Refreshing ${section}`,
      refreshFailed: 'Could not refresh. Try again.',
    },
    qrCode: {
      title: '§E1§ QR Code',
      projectLabel: '§E1§',
      slugLabel: 'Slug',
      helperText: 'Scan code to add §E8§ to this §E5§.',
      downloadPng: 'Download PNG',
      copyLink: 'Copy Link',
      copyLinkSuccess: 'Lead link copied to clipboard.',
      copyLinkError: 'Could not copy the lead link.',
      closeAriaLabel: 'Close §E5§ QR code dialog',
    },
    templates: {
      project: {
        actionsLoad: 'Load §E1§ Template',
        actionsSave: 'Save §E1§ Template',
        createSelectLabel: '§E1§ Template',
        createSelectPlaceholder: 'None',
        manageTemplatesAction: 'Manage Templates',
        save: {
          title: 'Save §E5§ template',
          nameLabel: 'Template name',
          namePlaceholder: 'e.g. Standard kitchen remodel',
          nameRequired: 'Template name is required.',
          confirm: 'Save §E1§ Template',
          saving: 'Saving…',
          cancel: 'Cancel',
          success: '§E1§ template saved.',
          failed: 'Could not save §E5§ template. Try again.',
          closeAriaLabel: 'Close save §E5§ template dialog',
          setAsDefaultLabel: 'Set as default §E5§ template',
          setAsDefaultHint: 'New §E6§ will start with this template applied to the draft.',
        },
        load: {
          title: 'Load §E5§ template',
          manageTitle: 'Manage §E5§ templates',
          manageNoneOption: 'None',
          manageNoneDescription: 'No template loads by default when creating a §E5§.',
          back: 'Back',
          backAriaLabel: 'Back to new §E5§',
          loading: 'Loading §E5§ templates…',
          empty: 'No saved §E5§ templates yet. Save one from Actions first.',
          loadFailed: 'Could not load §E5§ templates. Try again.',
          close: 'Close',
          closeAriaLabel: 'Close load §E5§ template dialog',
          createdLabel: (date: string): string => `Created ${date}`,
          countsLabel: (workflowCount: number, paymentCount: number): string =>
            `${workflowCount} workflow task${workflowCount === 1 ? '' : 's'} · ${paymentCount} payment${paymentCount === 1 ? '' : 's'}`,
          deleteAction: 'Delete',
          deleteAriaLabel: (name: string): string => `Delete ${name}`,
          itemLoadAction: 'Load',
          defaultBadge: 'Default',
          setDefaultTitle: 'Set as default §E5§ template',
          unsetDefaultTitle: 'Remove as default §E5§ template',
          setDefaultAriaLabel: (name: string): string => `Set ${name} as default §E5§ template`,
          unsetDefaultAriaLabel: (name: string): string =>
            `Remove ${name} as default §E5§ template`,
          setDefaultSuccess: 'Default §E5§ template updated.',
          unsetDefaultSuccess: 'Default §E5§ template removed.',
          setDefaultFailed: 'Could not update default §E5§ template.',
          applyConfirmTitle: 'Apply this §E5§ template?',
          applyConfirmMessage:
            'This will add workflow tasks and payments to the current §E5§.',
          applyDraftConfirmMessage:
            'This will add workflow tasks and payments to the new §E5§ draft.',
          applyConfirmLabel: 'Apply Template',
          applySuccess: '§E1§ template applied to this §E5§.',
          applyDraftSuccess: '§E1§ template applied to the new §E5§ draft.',
          applyFailed: 'Could not apply §E5§ template. Try again.',
          deleteConfirmTitle: 'Delete this §E5§ template?',
          deleteConfirmMessage: (name: string): string =>
            `"${name}" will be removed and cannot be restored.`,
          deleteConfirmLabel: 'Delete',
          deleteSuccess: '§E1§ template deleted.',
          deleteFailed: 'Could not delete §E5§ template. Try again.',
          draftTemplateApplied: (workflowCount: number, paymentCount: number): string =>
            `§E1§ template draft: ${workflowCount} workflow task${workflowCount === 1 ? '' : 's'}, ${paymentCount} payment${paymentCount === 1 ? '' : 's'} (applied on create).`,
        },
      },
      subproject: {
        actionsLoad: 'Load §E3§ Template',
        actionsSave: 'Save §E3§ Template',
        createSelectLabel: '§E3§ Template',
        createSelectPlaceholder: 'None',
        manageTemplatesAction: 'Manage Templates',
        save: {
          title: 'Save §E7§ template',
          nameLabel: 'Template name',
          namePlaceholder: 'e.g. Standard HVAC §E7§',
          nameRequired: 'Template name is required.',
          confirm: 'Save §E3§ Template',
          saving: 'Saving…',
          cancel: 'Cancel',
          success: '§E3§ template saved.',
          failed: 'Could not save §E7§ template. Try again.',
          closeAriaLabel: 'Close save §E7§ template dialog',
          setAsDefaultLabel: 'Set as default §E7§ template',
          setAsDefaultHint: 'New §E8§ will start with this template applied to the draft.',
        },
        load: {
          title: 'Load §E7§ template',
          manageTitle: 'Manage §E7§ templates',
          manageNoneOption: 'None',
          manageNoneDescription: 'No template loads by default when creating a §E7§.',
          back: 'Back',
          backAriaLabel: 'Back to new §E7§',
          loading: 'Loading §E7§ templates…',
          empty: 'No saved §E7§ templates yet. Save one from Actions first.',
          loadFailed: 'Could not load §E7§ templates. Try again.',
          close: 'Close',
          closeAriaLabel: 'Close load §E7§ template dialog',
          createdLabel: (date: string): string => `Created ${date}`,
          countsLabel: (workflowCount: number, paymentCount: number): string =>
            `${workflowCount} workflow task${workflowCount === 1 ? '' : 's'} · ${paymentCount} payment${paymentCount === 1 ? '' : 's'}`,
          deleteAction: 'Delete',
          deleteAriaLabel: (name: string): string => `Delete ${name}`,
          itemLoadAction: 'Load',
          defaultBadge: 'Default',
          setDefaultTitle: 'Set as default §E7§ template',
          unsetDefaultTitle: 'Remove as default §E7§ template',
          setDefaultAriaLabel: (name: string): string => `Set ${name} as default §E7§ template`,
          unsetDefaultAriaLabel: (name: string): string =>
            `Remove ${name} as default §E7§ template`,
          setDefaultSuccess: 'Default §E7§ template updated.',
          unsetDefaultSuccess: 'Default §E7§ template removed.',
          setDefaultFailed: 'Could not update default §E7§ template.',
          applyConfirmTitle: 'Apply this §E7§ template?',
          applyConfirmMessage:
            'This will add workflow tasks and payments to the current §E7§.',
          applyDraftConfirmMessage:
            'This will add workflow tasks and payments to the new §E7§ draft.',
          applyConfirmLabel: 'Apply Template',
          applySuccess: '§E3§ template applied to this §E7§.',
          applyDraftSuccess: '§E3§ template applied to the new §E7§ draft.',
          applyFailed: 'Could not apply §E7§ template. Try again.',
          deleteConfirmTitle: 'Delete this §E7§ template?',
          deleteConfirmMessage: (name: string): string =>
            `"${name}" will be removed and cannot be restored.`,
          deleteConfirmLabel: 'Delete',
          deleteSuccess: '§E3§ template deleted.',
          deleteFailed: 'Could not delete §E7§ template. Try again.',
          draftTemplateApplied: (workflowCount: number, paymentCount: number): string =>
            `§E3§ template draft: ${workflowCount} workflow task${workflowCount === 1 ? '' : 's'}, ${paymentCount} payment${paymentCount === 1 ? '' : 's'} (applied on create).`,
        },
      },
    },
    breadcrumbCrm: 'CRM',
    breadcrumbProjects: '§E2§',
    subprojects: {
      title: '§E4§',
      subprojectSingular: '§E7§',
      subprojectPlural: '§E8§',
      expand: 'Expand §E8§',
      collapse: 'Collapse §E8§',
      searchPlaceholder: 'Search §E8§…',
      searchAriaLabel: 'Search §E8§',
      newSubprojectTitle: 'New §E7§',
      newSubprojectAriaLabel: 'New §E7§',
      projectColumn: '§E3§',
      empty: 'No §E8§ yet.',
      emptyMemberNoAssignments: "You don't have any §E8§ assigned to you yet.",
      delete: {
        action: 'Delete §E3§',
        actionAriaLabel: (name: string): string => `Delete §E3§ ${name}`,
        confirmTitle: 'Delete this §E7§?',
        confirmMessage: (name: string): string =>
          `"${name}" will be permanently removed. This §E7§ and its data will no longer be accessible.`,
        success: '§E3§ deleted.',
        workflow: {
          title: 'Delete §E3§',
          itemLabel: '§E7§',
          intentActionLabel: 'I want to delete this §E7§',
          finalActionLabel: 'Delete §E3§',
          consequenceDescription:
            'This action permanently deletes this §E7§ and all associated data.',
          affectedDataSummary:
            'Affected data includes Workflow Tasks, Payments, Budget Entries, Documents, Reporting Data, and Accountability Records.',
        },
      },
      bulkDelete: {
        itemLabel: '§E7§',
        consequenceDescription:
          'This action permanently deletes the selected §E8§ and all associated data.',
        affectedDataSummary:
          'Affected data includes Workflow Tasks, Payments, Budget Entries, Documents, Reporting Data, and Accountability Records.',
      },
      markInactive: {
        title: 'Mark inactive',
        singleMessage: (name: string): string =>
          `Are you sure you want to make ${name} inactive?`,
        bulkMessage: (count: number): string =>
          `Are you sure you want to make ${count} §E8§ inactive?`,
        reasonLabel: 'Reason',
        reasonPlaceholder: 'Select a reason',
        customReasonLabel: 'Custom reason',
        reasonRequired: 'Reason is required.',
        customReasonRequired: 'Custom reason is required when Other is selected.',
        submit: 'Mark inactive',
        submitting: 'Marking inactive…',
        closeAriaLabel: 'Close mark inactive dialog',
        menuAction: 'Mark Inactive',
        menuActionAriaLabel: (name: string): string => `Mark ${name} inactive`,
        bulkMenuAction: 'Mark Inactive',
        success: '§E3§ marked inactive.',
        bulkSuccess: (count: number): string =>
          count === 1 ? '§E3§ marked inactive.' : `${count} §E8§ marked inactive.`,
        failed: 'Could not mark §E8§ inactive.',
        partialFailure: (updated: number, failed: number): string =>
          `Marked ${updated} inactive · ${failed} could not be updated`,
        badge: 'Inactive',
        inactiveReasonPrefix: 'Inactive:',
      },
      markActive: {
        menuAction: 'Mark Active',
        menuActionAriaLabel: (name: string): string => `Mark ${name} active`,
        bulkMenuAction: 'Mark Active',
        success: '§E3§ marked active.',
        bulkSuccess: (count: number): string =>
          count === 1 ? '§E3§ marked active.' : `${count} §E8§ marked active.`,
        failed: 'Could not mark §E7§ active.',
        partialFailure: (updated: number, failed: number): string =>
          `Marked ${updated} active · ${failed} could not be updated`,
        editRequiresActiveTitle: '§E1§ is inactive',
        editRequiresActiveMessage:
          'This §E5§ must be active before you can make edits. Mark it active now?',
        editRequiresActiveConfirm: 'Mark active',
        editRequiresActiveCancel: 'Cancel',
      },
      bulkSendAttachment: {
        title: 'Send attachment to selected items',
        sentTitle: 'Send complete',
        recipientsHeading: 'Recipients',
        selectedSummary: (count: number): string => `${count} selected`,
        readySummary: (count: number): string => `${count} recipients ready`,
        skippedSummary: (count: number): string => `${count} missing email`,
        showRecipients: 'Show recipients',
        hideRecipients: 'Hide recipients',
        unableToSend: 'Missing email',
        sendToRecipients: (count: number): string => `Send to ${count} recipients`,
        sendingProgress: (current: number, total: number): string => `Sending ${current} of ${total}…`,
        uploading: 'Uploading attachments…',
        completionSummary: (sent: number, failed: number, skipped: number): string =>
          `Sent ${sent} · Failed ${failed} · Skipped ${skipped}`,
        sendFailed: 'Could not send to all recipients. Review the summary and try again.',
        success: 'Emails sent to selected §E8§.',
        closeAriaLabel: 'Close bulk send attachment dialog',
        closeLabel: 'Close',
        resultsColumnSubproject: '§E3§',
        resultsColumnContact: 'Contact',
        resultsColumnEmail: 'Email',
        resultsColumnStatus: 'Status',
        statusSent: 'Sent',
        statusFailed: 'Failed',
        statusMissingEmail: 'Missing email',
        emptyCell: '—',
        resultsRegionAriaLabel: 'Bulk send results',
      },
    },
    saveSuccess: 'Changes saved.',
    saveError: 'Could not save changes.',
    communications: {
      sendAttachment: {
        title: 'Send attachment',
        sentTitle: 'Sent',
        toLabel: 'To',
        recipientPickerAriaLabel: 'Select recipient',
        recipientPickerPlaceholder: 'Select recipient',
        recipientGroupCustomer: 'Customer',
        recipientGroupMembers: 'Team Members',
        subjectLabel: 'Subject',
        messageLabel: 'Message',
        messagePlaceholder: 'Add a message (optional)...',
        attachmentsLabel: 'Attachments',
        uploadHint: 'Drag and drop files here, or click to choose files.',
        uploadMaxSizeNote: 'Up to {maxMb} MB per file.',
        existingDocumentsHeading: 'Add existing documents for this item',
        existingDocumentsEmpty: 'No documents are attached to this item yet.',
        addExistingFile: 'Add file',
        addedExistingFile: 'Added',
        selectedAttachmentsHeading: 'Attachments to send',
        removeSelectedFile: 'Remove',
        footerHelper: 'You can add multiple files.',
        cancel: 'Cancel',
        send: 'Send',
        sending: 'Sending…',
        success: 'Email sent with attachment(s).',
        sendFailed: 'Could not send the email. Try again.',
        closeAriaLabel: 'Close send attachment dialog',
      },
    },
    workflow: {
      empty: 'No workflow tasks for this §E5§.',
      searchPlaceholder: 'Search workflow tasks…',
      searchAriaLabel: 'Search workflow tasks',
      permissionsLoading: 'Loading workflow task permissions…',
      noViewPermission: 'You do not have permission to view workflow tasks.',
      noUploadPermission: 'You do not have permission to upload workflow task documents.',
      statusDoneNotAllowed: 'You do not have permission to mark tasks as done.',
      collapseStageTasks: 'Collapse stage tasks',
      expandStageTasks: 'Expand stage tasks',
      taskSingular: 'task',
      taskPlural: 'tasks',
      stageNoTasks: 'No tasks in this stage.',
      addTask: 'Add task',
      pickStage: 'Choose pipeline stage',
      taskAddedSuccess: 'Workflow task added.',
      saveTask: 'Save task',
      cancelTask: 'Cancel',
      editTask: 'Edit task',
      addNotes: 'Add notes',
      editNotes: 'Edit notes',
      sendCustomerNotification: 'Notify Assigned',
      notifyAssigned: 'Notify Assigned',
      sendAttachment: 'Send Attachment',
      taskActionsMenuAriaLabel: (title: string): string => `Actions for ${title}`,
      archiveTask: 'Archive',
      deleteTask: 'Delete task',
      archiveTaskConfirmTitle: 'Delete task?',
      archiveTaskConfirmLabel: 'Delete',
      archiveTaskCancelLabel: 'Cancel',
      archiveTaskSuccess: 'Task deleted.',
      archiveTaskFailed: 'Could not delete task.',
      bulkDeleteItemLabel: 'task',
      bulkChangeStatus: 'Change status',
      bulkArchiveConfirmTitle: (count: number): string =>
        count === 1 ? 'Delete selected task?' : `Delete ${count} selected tasks?`,
      bulkStatusChangeSuccess: (count: number): string =>
        count === 1 ? 'Updated status for 1 task.' : `Updated status for ${count} tasks.`,
      bulkStatusChangePartial: (updatedCount: number, skippedCount: number): string =>
        `Updated ${updatedCount} task${updatedCount === 1 ? '' : 's'}; ${skippedCount} skipped.`,
      bulkStatusChangeFailed: 'Could not update status for selected tasks.',
      bulkNotifyAssigned: 'Notify assigned',
      bulkNotifyConfirmTitle: (count: number): string =>
        count === 1
          ? 'Notify the assignee for the selected task?'
          : `Notify assignees for ${count} selected tasks?`,
      bulkNotifyConfirmLabel: 'Send emails',
      bulkNotifySuccess: (count: number): string =>
        count === 1
          ? 'Sent notification for 1 task.'
          : `Sent notifications for ${count} tasks.`,
      bulkNotifyPartial: (sentCount: number, skippedCount: number): string =>
        `Sent ${sentCount}; skipped ${skippedCount} (unassigned or no email).`,
      bulkNotifyFailed: 'Could not send notifications for selected tasks.',
      bulkNotifyNoneEligible:
        'None of the selected tasks have an assignee with an email address.',
      documentsNone: '—',
      documentsReview: 'Review files',
      documentsMarkRequired: 'Required',
      documentsNotRequired: 'N/A',
      documentsUpload: 'Upload',
      documentsUploadComingSoon: 'Uploads coming in a later phase.',
      documentUploadFailed: 'Could not upload document.',
      coreServicesUnavailable: 'Document storage is temporarily unavailable.',
      documentUploadSuccess: 'Document uploaded.',
      documentUploadConfirmTitle: 'Upload document?',
      documentUploadConfirmMessage: 'Upload “{fileName}” to “{taskTitle}”?',
      documentUploadConfirmLabel: 'Upload',
      documentDownload: 'Download',
      documentDelete: 'Delete',
      storageLimitExceeded: 'Could not upload file. Try again or contact support.',
      documentsCountSuffix: 'files',
      documentsPreviewHeading: (count: number): string =>
        count === 1 ? '1 attached document' : `${count} attached documents`,
      documentsPreviewMore: (count: number): string => `+${count} more`,
      documentsPreviewOpenHint: 'Open to view documents',
      documentsCountAriaLabel: (count: number): string =>
        count === 1 ? '1 file' : `${count} files`,
      notesFullPreviewAriaLabel: 'Full notes',
      unassigned: 'Unassigned',
      taskDoneIndicator: 'Task complete',
      taskOpenIndicator: 'Task not complete',
      stageAllDone: 'All tasks in this stage are complete',
      stageNotComplete: 'Stage has incomplete tasks',
      markStageCompleteConfirmTitle: (stageName: string) =>
        `${stageName} has no tasks. Are you sure you want to mark this stage complete?`,
      markStageComplete: 'Mark Complete',
      markStageCompleteSuccess: 'Stage marked as complete.',
      markStageCompleteFailed: 'Could not mark stage as complete.',
      markStageIncompleteConfirmTitle: 'Mark this stage incomplete?',
      markStageIncomplete: 'Mark Incomplete',
      markStageIncompleteSuccess: 'Stage marked as incomplete.',
      markStageIncompleteFailed: 'Could not mark stage as incomplete.',
      markAllEmptyStagesComplete: 'Mark All Complete',
      markAllEmptyStagesCompleteConfirmTitle:
        'Are you sure you want to mark all stages complete?',
      markAllEmptyStagesCompleteSuccess: 'Empty stages marked as complete.',
      markAllEmptyStagesCompleteFailed: 'Could not mark empty stages as complete.',
      markAllEmptyStagesCompleteNone: 'No empty incomplete stages to mark complete.',
      markAllEmptyStagesCompleteAction: 'Mark all empty stages complete',
      markAllEmptyStagesCompleteAllDone: 'All workflow stages are complete',
      taskModalCreate: 'Create workflow task',
      taskModalEdit: 'Edit workflow task',
      taskModalCloseAriaLabel: 'Close workflow task dialog',
      taskSubmitCreate: 'Create task',
      taskSubmit: 'Save task',
      taskSubmitting: 'Saving…',
      taskSubmitFailed: 'Failed to save task.',
      discardChangesTitle: 'Discard unsaved changes?',
      discardChangesMessage: 'You have unsaved changes. Close without saving?',
      discardChangesConfirm: 'Discard changes',
      modalSections: {
        taskInformation: 'Task information',
        assignment: 'Assignment',
        details: 'Details',
        customFields: 'Custom fields',
      },
      paymentsGroupLabel: 'Payments',
      taskKindStandard: 'Standard task',
      taskKindPayment: 'Payment milestone',
      columns: {
        task: 'Task',
        stage: 'Stage',
        status: 'Status',
        documents: 'Documents',
        amount: 'Amount',
        assigned: 'Assigned',
        due: 'Due',
        notes: 'Notes',
        actions: 'Actions',
      },
      viewAll: 'View all Workflow Tasks',
      viewMode: {
        switchToCards: 'Show stages as cards',
        switchToTable: 'Show stages as table',
      },
      usersColumn: 'Users',
      usersColumnLoading: 'Loading users…',
      usersColumnEmpty: 'No users',
      usersColumnTaskCount: (count: number): string =>
        `${count} ${count === 1 ? 'task' : 'tasks'}`,
      usersColumnDragHint: 'Drag to a task to assign',
      usersColumnDragLabel: (displayName: string): string => `Assigning ${displayName}`,
      openDocuments: 'Documents',
      fields: {
        title: 'Task title',
        stage: 'Stage',
        status: 'Status',
        documentsRequired: 'Documents required',
        documentsRequiredYes: 'Yes',
        documentsRequiredNo: 'No',
        due: 'Due date',
        notes: 'Notes',
        assigned: 'Assigned to',
        taskKind: 'Task type',
        amountUsd: 'Amount (USD)',
      },
      customFields: {
        sectionTitle: 'Custom fields',
        empty: 'No custom fields yet.',
        addButton: '+ Add custom field',
        addDialogTitle: 'Add custom field',
        labelField: 'Label',
        typeField: 'Type',
        typeText: 'Text',
        addConfirm: 'Add field',
        creating: 'Adding…',
        createFailed: 'Could not create custom field.',
        closeAriaLabel: 'Close add custom field dialog',
        unsupportedType: 'This field type is not supported yet.',
        selectMember: 'Select Member',
        newFieldLabelPlaceholder: 'Field name',
        saveNewField: 'Add',
        cancelNewField: 'Cancel',
        renameFailed: 'Could not rename custom field.',
        removeAriaLabel: (label: string): string => `Delete custom field ${label}`,
        fieldMenuAriaLabel: (label: string): string => `Options for ${label}`,
        renameAction: 'Rename',
        deleteAction: 'Delete',
        deleteField: {
          title: (label: string): string => `Delete "${label}"?`,
          body: 'This will remove the field from all workflow tasks in your organization, and any values stored in this field will be erased.',
          confirm: 'Delete field',
          cancel: 'Cancel',
          deleting: 'Deleting…',
          failed: 'Could not delete custom field.',
          closeAriaLabel: 'Close delete custom field dialog',
        },
      },
      tableColumns: {
        addColumn: '+ Column',
        addColumnAriaLabel: 'Add custom column',
        pickerTitle: 'Show Custom Field',
        createCustomField: '+ Create Custom Field',
        noCustomFields: 'No custom fields yet. Create one first.',
        menuAriaLabel: 'Column options',
        replaceColumn: 'Replace Column…',
        removeFromTable: 'Remove From Table',
        renameField: 'Rename Field…',
        archiveField: 'Archive Field…',
        setColumnFailed: 'Could not update table column.',
        renameFailed: 'Could not rename custom field.',
        archiveFailed: 'Could not archive custom field.',
        emptyValue: '—',
      },
      preview: {
        ariaLabel: (title: string): string => `Task preview for ${title}`,
        showPreviewAriaLabel: (title: string): string => `Show preview for ${title}`,
        hidePreviewAriaLabel: 'Hide task preview',
        kindTask: 'Task',
        kindPayment: 'Payment',
        labels: {
          stage: 'Stage',
          amount: 'Amount',
        },
        documentsNa: 'N/A',
        documentOneFile: '1 file',
        documentFiles: (count: number): string => `${count} files`,
        dateNa: 'N/A',
        sections: {
          overview: 'Overview',
          details: 'Details',
          notes: 'Notes',
          customFields: 'Custom fields',
        },
        openDetails: 'Open details',
      },
      assignedNotify: {
        title: 'Notify assigned?',
        messageWithEmail: (recipientName: string) =>
          `Would you like to email ${recipientName} about this task?`,
        messageNoEmail:
          'The assigned person does not have an email address on file, so no notification can be sent.',
        notNow: 'Not now',
        sendEmail: 'Send email',
        sending: 'Sending…',
        sentTitle: 'Sent',
        success: 'Notification email sent.',
        sendFailed: 'Could not send the notification email. Try again.',
        closeAriaLabel: 'Close notify assigned dialog',
      },
      customerNotify: {
        title: 'Notify customer?',
        messageWithEmail: (customerName: string) =>
          `Would you like to email ${customerName} about this task?`,
        messageNoEmail:
          'This customer does not have an email address on file, so no notification can be sent.',
        notNow: 'Not now',
        sendEmail: 'Send email',
        sending: 'Sending…',
        sentTitle: 'Sent',
        success: 'Notification email sent.',
        sendFailed: 'Could not send the notification email. Try again.',
        closeAriaLabel: 'Close notify customer dialog',
      },
    },
    payments: {
      title: 'Payments',
      memberTitle: 'Payment Tasks',
      searchPlaceholder: 'Search payments…',
      searchAriaLabel: 'Search payments',
      addMilestone: 'Add payment milestone',
      empty: 'No payment milestones yet.',
      columns: {
        invoiced: 'Invoiced',
        paid: 'Paid',
      },
      milestoneDrawerCreate: 'New payment milestone',
      milestoneDrawerEdit: 'Edit payment milestone',
      saveMilestone: 'Save payment milestone',
      cancelMilestone: 'Cancel',
      customFields: {
        sectionTitle: 'Payment custom fields',
        empty: 'No payment custom fields yet.',
        addButton: '+ Add payment custom field',
        addDialogTitle: 'Add payment custom field',
        labelField: 'Label',
        typeField: 'Type',
        typeText: 'Text',
        addConfirm: 'Add field',
        creating: 'Adding…',
        createFailed: 'Could not create payment custom field.',
        closeAriaLabel: 'Close add payment custom field dialog',
        unsupportedType: 'This field type is not supported yet.',
      },
      tableColumns: {
        addColumn: '+ Column',
        addColumnAriaLabel: 'Add custom column',
        pickerTitle: 'Show Custom Field',
        createCustomField: '+ Create Custom Field',
        noCustomFields: 'No custom fields yet. Create one first.',
        menuAriaLabel: 'Column options',
        replaceColumn: 'Replace Column…',
        removeFromTable: 'Remove From Table',
        renameField: 'Rename Field…',
        archiveField: 'Archive Field…',
        setColumnFailed: 'Could not update table column.',
        renameFailed: 'Could not rename custom field.',
        archiveFailed: 'Could not archive custom field.',
        emptyValue: '—',
      },
      preview: {
        ariaLabel: (title: string): string => `Payment preview for ${title}`,
        showPreviewAriaLabel: (title: string): string => `Show preview for ${title}`,
        hidePreviewAriaLabel: 'Hide payment preview',
        kindTask: 'Task',
        kindPayment: 'Payment',
        labels: {
          stage: 'Stage',
          amount: 'Amount',
        },
        documentsNa: 'N/A',
        documentOneFile: '1 file',
        documentFiles: (count: number): string => `${count} files`,
        dateNa: 'N/A',
        sections: {
          overview: 'Overview',
          details: 'Details',
          notes: 'Notes',
          customFields: 'Custom fields',
        },
        openDetails: 'Open details',
      },
    },
    documents: {
      empty: 'No documents yet.',
      searchPlaceholder: 'Search documents…',
      searchAriaLabel: 'Search documents',
      uploadHint: 'Upload photos, videos, and documents to this §E5§.',
      filterAriaLabel: 'Filter documents',
      filters: {
        all: 'All',
        uploaded: 'Uploaded',
        missing: 'Missing',
      },
      noStage: 'No stage',
      missingForTask: 'Required for task',
      missingForBudgetEntry: 'Required for budget item',
      uploadedForBudgetEntry: 'Budget item',
      placeholderMeta: 'Required · not uploaded',
      placeholders: ['Signed estimate', 'Site photos', 'Permit packet'],
      viewAll: 'View all documents',
      bulkDeleteItemLabel: 'document',
      bulkDeleteConfirmTitle: (count: number): string =>
        count === 1
          ? 'Delete selected document?'
          : `Delete ${count} selected documents?`,
      bulkDownloadDocument: 'Download document',
      bulkDownloadDocuments: 'Download selected documents',
      bulkDownloadFailed: 'Could not download selected documents. Try again.',
      columns: {
        name: 'Document',
        kind: 'Type',
        stage: 'Stage',
        uploaded: 'Uploaded',
        status: 'Status',
      },
      statusReviewed: 'Reviewed',
      statusPending: 'Pending review',
    },
    accountability: {
      empty: 'No activity logged yet.',
      searchPlaceholder: 'Search accountability…',
      searchAriaLabel: 'Search accountability',
      viewAll: 'View all Accountability',
      columns: {
        dateTime: 'Date / Time',
        user: 'User',
        event: 'Event',
        entity: 'Entity',
        details: 'Details',
      },
    },
    budget: {
      tableTitle: 'Budget',
      searchPlaceholder: 'Search budget…',
      searchAriaLabel: 'Search budget',
      addItem: 'Add budget item',
      addItemRowLabel: 'Add Budget Item',
      documentsAdd: 'Add',
      documentsUploadAfterSave: 'Save the budget item to upload documents',
      empty: 'No budget items yet.',
      filterAriaLabel: 'Filter budget',
      itemNameRequired: 'Item name is required.',
      itemNamePlaceholder: 'Item name',
      saveItem: 'Save budget item',
      cancelItem: 'Cancel',
      deleteItem: 'Delete budget item',
      deleteItemConfirmTitle: 'Delete budget item?',
      deleteItemConfirmLabel: 'Delete',
      deleteItemCancelLabel: 'Cancel',
      deleteItemSuccess: 'Budget item deleted.',
      deleteItemFailed: 'Could not delete budget item.',
      bulkDeleteItemLabel: 'budget item',
      bulkDeleteConfirmTitle: (count: number): string =>
        `Delete ${count} budget item${count === 1 ? '' : 's'}?`,
      totalsLabel: 'Totals',
      columns: {
        itemName: 'Item Name',
        category: 'Category',
        cost: 'Cost',
        budget: 'Budget',
        costDate: 'Cost Date',
        documents: 'Documents',
        remaining: 'Remaining',
      },
      costDateRequired: 'Cost Date is required.',
      categoryLabels: {
        labor: 'Labor',
        materials: 'Materials',
        equipment: 'Equipment',
        subcontractors: 'Subcontractors',
        permits: 'Permits',
        travel: 'Travel',
        lodging: 'Lodging',
        per_diem: 'Per Diem',
        fuel: 'Fuel',
        dump_disposal: 'Dump / Disposal Fees',
        rental_fees: 'Rental Fees',
        insurance: 'Insurance',
        office_admin: 'Office / Admin',
        other: 'Other',
      },
      pl: {
        title: '§E1§ Cost',
        generatePl: 'Generate P&L',
        exportError: 'Could not generate the P&L PDF. Please try again.',
        categoryName: 'Name',
        categoryCost: 'Cost',
        noCategories: 'No costs recorded yet.',
        totalBudget: 'Total Budget',
        totalCost: 'Total Cost',
        remaining: 'Remaining',
        overBudget: 'Over Budget',
        dealValue: 'Contract value (reference)',
      },
    },
    projectReport: {
      title: '§E1§ Financial Report',
      downloadPdf: 'Download PDF',
      exportError: 'Could not generate the report PDF. Please try again.',
      summaryTitle: 'Financial Summary',
      value: 'Value',
      collected: 'Collected',
      balance: 'Balance',
      costs: 'Costs',
      actualProfit: 'Actual Profit',
      projectedProfit: 'Projected Profit',
      paymentsTitle: 'Payments',
      costsTitle: 'Costs',
      graphTitle: 'Cost Breakdown',
      projectColumn: '§E1§',
      paymentColumn: 'Payment',
      amount: 'Amount',
      status: 'Status',
      paidDate: 'Paid Date',
      paidIndicator: 'Paid',
      category: 'Category',
      percentOfCosts: '% of Costs',
      itemCount: 'Items',
      paid: 'Paid',
      unpaid: 'Unpaid',
      noPayments: 'No payment milestones recorded.',
      noCosts: 'No costs recorded yet.',
    },
  },
  leadCapture: {
    loading: 'Loading…',
    intro: 'Connect with this project by filling out the form below.',
    invalidTitle: 'Link unavailable',
    invalidMessage: 'This lead link is invalid or no longer active.',
    successTitle: 'Thank you',
    successMessage: 'Your information has been sent.',
    form: {
      firstNameLabel: 'First name',
      lastNameLabel: 'Last name',
      emailAddressesLabel: 'Email addresses (up to 4)',
      phoneNumbersLabel: 'Phone numbers (up to 4)',
      addEmail: '+ Add email',
      addPhone: '+ Add phone',
      removeEmail: 'Remove email address',
      removePhone: 'Remove phone number',
      removeEmailConfirm: {
        title: 'Remove email address?',
        body: 'This email address will be removed from your submission.',
        confirm: 'Remove',
        cancel: 'Cancel',
        closeAriaLabel: 'Close remove email dialog',
      },
      removePhoneConfirm: {
        title: 'Remove phone number?',
        body: 'This phone number will be removed from your submission.',
        confirm: 'Remove',
        cancel: 'Cancel',
        closeAriaLabel: 'Close remove phone dialog',
      },
      addressLine1Label: 'Address',
      addressLine2Label: 'Address line 2 (optional)',
      cityLabel: 'City',
      stateLabel: 'State',
      statePlaceholder: 'Select state',
      postalCodeLabel: 'ZIP',
      submit: 'Submit',
      submitting: 'Submitting…',
      submitFailed: 'Could not submit your information. Try again.',
    },
  },
  customerTaskPortal: {
    loading: 'Loading task…',
    invalidTitle: 'Link unavailable',
    invalidMessage: 'This task link is invalid or has already been used.',
    expiredTitle: 'Link expired',
    expiredMessage: 'This task link has expired. Contact your contractor for a new link.',
    submittedTitle: 'Thank you',
    submittedMessage: 'Your response was submitted. The team will review it shortly.',
    projectLabel: 'Project',
    taskLabel: 'Task',
    instructionsLabel: 'Instructions',
    responseLabel: 'Your response',
    responsePlaceholder: 'Add any notes or details for the team (optional).',
    uploadLabel: 'Upload files',
    uploadHint: 'Drag and drop files here, or choose files from your device. Files are sent when you submit.',
    chooseFiles: 'Choose files',
    selectedFiles: 'Selected files',
    uploadedFiles: 'Uploaded files',
    submit: 'Submit',
    submitting: 'Submitting…',
    uploadError: 'Could not upload file.',
    removeFile: 'Remove file',
    removeFileError: 'Could not remove file.',
    submitError: 'Could not submit your response. Try again.',
  },
} as const;

export type BuildCoreDashboardContent = ReturnType<typeof createBuildCoreDashboardContent>;

export function createBuildCoreDashboardContent(
  terms: ResolvedEntityTerminology = resolveEntityTerminology()
) {
  return deepResolveEntityTerminologyTokens(buildCoreDashboardContentSource, terms);
}

let activeDashboardContent = createBuildCoreDashboardContent();

export function bindBuildCoreDashboardContent(terms: ResolvedEntityTerminology): void {
  activeDashboardContent = createBuildCoreDashboardContent(terms);
}

export function getBuildCoreDashboardContent() {
  return activeDashboardContent;
}

/** Live-bound content. Prefer reading during render after EntityTerminologyProvider binds terms. */
export const buildCoreDashboardContent = new Proxy(
  {} as ReturnType<typeof createBuildCoreDashboardContent>,
  {
    get(_target, prop, receiver) {
      const current = activeDashboardContent;
      const value = Reflect.get(current as object, prop, receiver);
      return typeof value === 'function' ? (value as Function).bind(current) : value;
    },
    ownKeys() {
      return Reflect.ownKeys(activeDashboardContent as object);
    },
    getOwnPropertyDescriptor(_target, prop) {
      return Reflect.getOwnPropertyDescriptor(activeDashboardContent as object, prop);
    },
    has(_target, prop) {
      return Reflect.has(activeDashboardContent as object, prop);
    },
  }
);
