export {
  createStaffMember,
  deleteStaffMember,
  getAppEntitlement,
  getCoreHealth,
  getMyAppConfig,
  getMyProfile,
  getRegisteredApp,
  getSessionMe,
  getStaffMember,
  listStaffMembers,
  patchMyAppConfig,
  patchMyProfile,
  updateStaffMember,
} from '@/infrastructure/coreApi/client';
export type { GetAppEntitlementOptions } from '@/infrastructure/coreApi/client';
export { diagnoseZenformedCoreConnectivity } from '@/infrastructure/coreApi/diagnostics';
export type {
  CoreApiError,
  CoreApiResult,
  ZenformedCoreAppConfigPatchOk,
  ZenformedCoreAppEntitlementEnvelope,
  ZenformedCoreAppEntitlementWireResponse,
  ZenformedCoreEntitlementAuthorityMode,
  ZenformedCoreEntitlementServerAuthority,
  ZenformedCoreHealthBody,
  ZenformedCoreProfileDto,
  ZenformedCoreProfileEnvelope,
  ZenformedCoreProfilePatchRequest,
  ZenformedCoreRegisteredApp,
  ZenformedCoreRegisteredAppEnvelope,
  ZenformedCoreSessionMeBody,
  ZenformedCoreStaffDeleteOk,
  ZenformedCoreStaffMemberDto,
  ZenformedCoreStaffMemberEnvelope,
  ZenformedCoreStaffMemberRole,
  ZenformedCoreStaffMembersListEnvelope,
  ZenformedCoreUserAppConfigEnvelope,
} from '@/infrastructure/coreApi/types';
